name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  lint:
    name: Test Linting
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -U black flake8
    - name: Black
      run: |
          black --check .
    - name: Flake8
      run: |
          flake8 . --max-line-length=99

  docs:
    name: Test docs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -U sphinx
    - name: Build docs
      run: |
          cd docs
          make html

  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: Linux py37
            os: ubuntu-latest
            pyversion: '3.7'
          - name: Linux py38
            os: ubuntu-latest
            pyversion: '3.8'
          - name: Linux py39
            os: ubuntu-latest
            pyversion: '3.9'
          - name: Windows py311
            os: windows-latest
            pyversion: '3.11'
          - name: MacOS py311
            os: macos-latest
            pyversion: '3.11'

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.pyversion }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.pyversion }}
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install pytest pytest-cov
      - name: Test with pytest
        run: |
            pip install .
            pytest -v --cov=itemdb .
