name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  lint:
    name: Test Linting
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install ruff
    - name: Ruff lint
      run: |
          ruff check --output-format=github .
    - name: Ruff format
      run: |
          ruff format --check .

  docs:
    name: Test Docs
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dev dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -U -e .[docs]
    - name: Build docs
      run: |
          cd docs
          make html SPHINXOPTS="-W --keep-going"

  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux py38
            os: ubuntu-latest
            pyversion: '3.8'
          - name: Linux py39
            os: ubuntu-latest
            pyversion: '3.9'
          - name: Linux py310
            os: ubuntu-latest
            pyversion: '3.10'
          - name: Linux py311
            os: ubuntu-latest
            pyversion: '3.11'
          - name: Linux py312
            os: ubuntu-latest
            pyversion: '3.12'
          - name: Linux py313
            os: ubuntu-latest
            pyversion: '3.13'
          #
          - name: Windows py313
            os: windows-latest
            pyversion: '3.13'
          - name: MacOS py313
            os: macos-latest
            pyversion: '3.13'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.pyversion }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.pyversion }}
      - name: Install dependencies
        shell: bash
        run: |
            python -m pip install --upgrade pip
            pip install pytest pytest-cov
            pip install .
            rm -rf ./itemdb.py ./build ./egg-info
      - name: Test with pytest
        run: |
            pytest -v --cov=itemdb .
